# Generated by Django 6.0.6 on 2026-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='Archivo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created'],
            },
        ),
    ]
